version: '3'

services:
  mysql-wordpress:
    image: mysql:latest
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      network: db

  wordpress:
    depends_on:
      - mysql-wordpress
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_DOMAIN}`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html
    networks: 
      - traefik

networks:
  traefik:
    external: true # Use external network named "traefik"
  db:
    external: true # Use external network named "db"

