{
 "title": "Jenkins Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "folder",
    "label": "Folder",
    "query": "SHOW TAG VALUES FROM job WITH KEY = \"owner\"\n"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "SHOW TAG VALUES FROM job WITH KEY = repo WHERE \"owner\" =~ /^($folder)$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Jenkins Status",
   "type": "stat",
   "description": "Jenkins Status",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_online_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Success",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'SUCCESS' OR \"build_result\" = 'CompletedSuccess' ) AND $timeFilter "
    },
    {
     "alias": "Failure",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'FAILURE' OR \"build_result\" = 'CompletedError' ) AND $timeFilter "
    },
    {
     "alias": "Aborted",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'ABORTED' OR \"build_result\" = 'Aborted' ) AND $timeFilter "
    },
    {
     "alias": "Unstable",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'UNSTABLE' OR \"build_result\" = 'Unstable' ) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Number of Pipelines Ran",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select count(DISTINCT project_name) FROM jenkins_data WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Total number of builds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Average Build Time ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select build_time/1000 FROM jenkins_data WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Active Plugins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Plugins with Updates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_withUpdate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inactive Plugins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest Build Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT build_result FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter  ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Jenkins node, queue, executor stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "jenkins_executor_count_value\r\n",
     "legendFormat": "__auto"
    },
    { "expr": "jenkins_queue_size_value", "legendFormat": "__auto" },
    { "expr": "jenkins_node_count_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Build Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"build_exec_time\",\"project_path\",\"build_number\",\"build_causer\",\"build_time\",\"build_result\" FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter "
    }
   ]
  }
 ]
}